/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    java
    kotlin("jvm") version "1.7.20"
    id("io.github.lhotari.gradle-nar-plugin") version "0.5.1"
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation("org.apache.nifi:nifi-api:1.16.0")
    implementation("org.apache.nifi:nifi-utils:1.16.0")
    implementation("org.apache.nifi:nifi-processor-utils:1.15.3")
    implementation("org.jetbrains.kotlin:kotlin-stdlib:1.7.20")
    implementation("org.apache.nifi:nifi-ssl-context-service-api:1.16.0")
    implementation("org.apache.nifi:nifi-standard-services-api-nar:1.16.0")
    implementation("org.apache.nifi:nifi-standard-web-test-utils:1.15.3")
    implementation("commons-net:commons-net:3.6")
    testImplementation("org.apache.nifi:nifi-mock:1.16.0")
    testImplementation("org.mockito:mockito-core:3.11.2")
    testImplementation("junit:junit:4.13.2")
}

group = "net.nerdfunk"
version = "1.0"
description = "nerdfunk-flow2network-processors"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}
