name: Gradle Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@27152f6fa06a6b8062ef7195c795692e51fc2c81

      - name: Assemble .nar artifact with Gradle
        uses: gradle/gradle-build-action@3b1b3b9a2104c2b47fbae53f3938079c00c9bb87
        with:
          arguments: assemble

      - name: Check project with Gradle
        uses: gradle/gradle-build-action@3b1b3b9a2104c2b47fbae53f3938079c00c9bb87
        with:
          arguments: check

      - name: Run integration tests with Gradle
        uses: gradle/gradle-build-action@3b1b3b9a2104c2b47fbae53f3938079c00c9bb87
        with:
          arguments: integrationTest

      ## Artifacts ##
      - name: Upload test results for debugging purposes
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: test-report
          path: build/reports/tests/
          if-no-files-found: warn
      - name: Upload Apache NiFi logs for debugging purposes
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: nifi-logs
          path: src/integrationTest/resources/mounted-directory/nifi-logs/
          if-no-files-found: warn

      - name: Upload built .nar artifact
        uses: actions/upload-artifact@v4
        with:
          name: nar
          path: build/libs/*.nar
          if-no-files-found: error