name: Gradle Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@8d49e559aae34d3e0eb16cde532684bc9702762b

      - name: Assemble .nar artifact with Gradle
        uses: gradle/gradle-build-action@40b6781dcdec2762ad36556682ac74e31030cfe2
        with:
          arguments: assemble

      - name: Check project with Gradle
        uses: gradle/gradle-build-action@40b6781dcdec2762ad36556682ac74e31030cfe2
        with:
          arguments: check

      - name: Run integration tests with Gradle
        uses: gradle/gradle-build-action@40b6781dcdec2762ad36556682ac74e31030cfe2
        with:
          arguments: integrationTest

      ## Artifacts ##
      - name: Upload test results for debugging purposes
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: test-report
          path: build/reports/tests/
          if-no-files-found: warn
      - name: Upload Apache NiFi logs for debugging purposes
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: nifi-logs
          path: src/integrationTest/resources/mounted-directory/nifi-logs/
          if-no-files-found: warn

      - name: Upload built .nar artifact
        uses: actions/upload-artifact@v3
        with:
          name: nar
          path: build/libs/*.nar
          if-no-files-found: error