name: Gradle Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@55e685c48d84285a5b0418cd094606e199cca3b6
      - name: Build with Gradle
        uses: gradle/gradle-build-action@6095a76664413da4c8c134ee32e8a8ae900f0f1f
        with:
          arguments: build
      - uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: build/reports/tests/
          if-no-files-found: error
      - uses: actions/upload-artifact@v3
        with:
          name: nar
          path: build/libs/*.nar
          if-no-files-found: error